const $ = s => document.querySelector(s), app = $('#app');
const R = { oil:{n:'النفط',i:'🛢️'}, gas:{n:'الغاز',i:'🔥'}, gold:{n:'الذهب',i:'🪙'}, iron:{n:'الحديد',i:'⚙️'} };
const PHASES = {lobby:'اللوبي',ship:'اختيار الباخرة',auction:'مزاد الأراضي',questionSelect:'اختيار السؤال',question:'الأسئلة',market:'السوق والمقايضات',stocks:'سوق الأسهم',news:'نشرة الأخبار',finished:'النتيجة'};
let session = JSON.parse(localStorage.getItem('oil-land-session') || 'null');
let state = null, poller = null, clock = null, lastRender = '', selectedLand = null, bidAmount = 500;
const fmt = n => new Intl.NumberFormat('ar-SA').format(n || 0);

function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function api(action, extra={}){const payload={action,...extra};if(session){payload.code=session.code;payload.token=session.token}const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw Error(data.error||'تعذر تنفيذ الطلب');if(action==='create'||action==='join')return data;if(data.state)return data.state;return data}
function saveSession(value){session=value;localStorage.setItem('oil-land-session',JSON.stringify(value))}
function clearSession(){session=null;state=null;localStorage.removeItem('oil-land-session');clearInterval(poller);location.href='/'}

function home(){const code=new URLSearchParams(location.search).get('room')?.toUpperCase();app.innerHTML=`<div class="screen"><div class="noise"></div><div class="hero"><div class="brand"><small>لعبة جماعية مباشرة</small><h1>أرض<br>النفط</h1><p>أنشئ غرفة واعرض الباركود، أو ادخل رمز الغرفة من جوالك وانضم إلى سباق القباطنة.</p>${code?`<div class="join-box"><div class="room-chip">الغرفة ${code}</div><input id="captainName" class="input" maxlength="20" placeholder="اسم القبطان"><button class="btn" onclick="joinRoom('${code}')">دخول الغرفة</button><button class="btn ghost" onclick="location.href='/'">رجوع</button></div>`:`<div class="home-actions"><button class="btn" onclick="createRoom()">إنشاء غرفة جديدة</button><button class="btn secondary" onclick="showJoin()">دخول برمز غرفة</button></div><div id="joinArea"></div>`}</div><div class="hero-art"></div></div></div>`}
function showJoin(){$('#joinArea').innerHTML=`<div class="join-box"><input id="roomCode" class="input" maxlength="5" placeholder="رمز الغرفة"><input id="captainName" class="input" maxlength="20" placeholder="اسم القبطان"><button class="btn" onclick="joinRoom()">انضمام</button></div>`}
async function createRoom(){try{const used=JSON.parse(localStorage.getItem('oil-land-used-questions-v1')||'[]');const data=await api('create',{usedQuestionIds:used});saveSession({code:data.code,token:data.token,role:'host'});state=data.state;startPolling();render()}catch(e){toast(e.message)}}
async function joinRoom(forced){try{const code=(forced||$('#roomCode')?.value||'').trim().toUpperCase(),name=$('#captainName').value.trim();if(!code||!name)return toast('اكتب الرمز واسم القبطان');const old=session;session={code,token:'',role:'player'};const data=await api('join',{name});saveSession({code,token:data.token,role:'player'});state=data.state;startPolling();render()}catch(e){session=null;toast(e.message)}}
async function refresh(){if(!session)return;try{const next=await api('state');if(next.usedQuestionIds)localStorage.setItem('oil-land-used-questions-v1',JSON.stringify(next.usedQuestionIds));const signature=JSON.stringify(next);state=next;if(signature!==lastRender){lastRender=signature;render()}updateClock()}catch(e){toast(e.message);if(/غير موجودة|رمز/.test(e.message))clearSession()}}
function startPolling(){clearInterval(poller);poller=setInterval(refresh,1000);startClock()}
function startClock(){clearInterval(clock);clock=setInterval(updateClock,250)}
function updateClock(){const el=$('#globalClock');if(!el||!state)return;const left=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));el.textContent=state.deadline?left:'--';el.parentElement?.classList.toggle('danger',left<=10&&left>0)}
function top(){return `<div class="topbar"><div class="logo">أرض النفط <small>#${state.code}</small></div><div class="stats"><div class="pill">${PHASES[state.phase]}</div><div class="pill">الجولة <b>${state.round}</b></div>${state.me?`<div class="pill">الرصيد <b>${fmt(state.me.cash)}</b></div>`:''}<div class="clock-ring"><small>الوقت</small><b id="globalClock">--</b></div></div></div>`}
function shell(content,bg=''){app.innerHTML=`<div class="screen online-screen"><div class="noise"></div>${bg}${top()}<main class="main">${content}</main></div>`;updateClock()}
function playerList(){return `<div class="online-players">${state.players.map(p=>`<div class="online-player ${p.connected?'':'offline'}"><i>${p.shipChosen?'🚢':'⚓'}</i><b>${p.name}</b><small>${p.connected?'متصل':'غير متصل'}</small></div>`).join('')}</div>`}

function render(){if(!state)return home();if(state.host)renderHost();else renderPlayer()}
function renderHost(){if(state.phase==='lobby')return hostLobby();if(state.phase==='auction')return hostAuction();if(state.phase==='news')return newsScreen(true);if(state.phase==='finished')return resultScreen();const done=state.phase==='ship'?state.players.filter(p=>p.shipChosen).length:state.phase==='questionSelect'?state.players.filter(p=>p.answered||false).length:state.phase==='question'?state.players.filter(p=>p.answered).length:0;shell(`<section class="host-stage"><span class="step">شاشة المضيف</span><h1>${PHASES[state.phase]}</h1><p>${state.message}</p>${playerList()}${state.phase==='market'?marketBoard():''}${state.phase==='stocks'?stockBoard(true):''}<button class="btn host-next" onclick="advance()">تقديم المرحلة الآن</button></section>`,state.phase==='market'||state.phase==='stocks'?'<div class="market-bg"></div>':'')}
function hostLobby(){const joinUrl=`${location.origin}/?room=${state.code}`;shell(`<section class="lobby-layout"><div><span class="step">غرفة جديدة</span><h1>امسح الباركود وانضم</h1><div class="code-big">${state.code}</div><p>${state.players.length} قباطنة متصلون</p>${playerList()}<button class="btn" ${state.players.length<2?'disabled':''} onclick="startGame()">ابدأ اللعبة</button><button class="btn ghost" onclick="clearSession()">إغلاق الغرفة</button></div><div class="qr-card"><img src="/api/qr?text=${encodeURIComponent(joinUrl)}" alt="باركود الدخول"><small>${joinUrl}</small></div></section>`,`<div class="lands-bg"></div>`)}
function hostAuction(){const current=state.players.find(p=>p.id===state.auction?.currentPlayerId);shell(`<div class="stage-head"><div><span class="step">مزاد مباشر</span><h2>الدور على ${current?.name||'حسم النتائج'}</h2><p>تظهر أسماء القباطنة ومبالغهم على الأراضي مباشرة.</p></div></div>${auctionBoard(false)}<button class="btn host-next" onclick="advance()">إنهاء الدور الحالي</button>`,`<div class="lands-bg"></div>`)}
function marketBoard(){return `<div class="market-public">${Object.keys(R).map(k=>`<div><span>${R[k].i} ${R[k].n}</span><b>${fmt(state.prices[k])}</b></div>`).join('')}</div>`}

function renderPlayer(){if(state.phase==='lobby')return waiting();if(state.phase==='ship')return chooseShip();if(state.phase==='auction')return playerAuction();if(state.phase==='questionSelect')return chooseQuestion();if(state.phase==='question')return answerQuestion();if(state.phase==='market')return market();if(state.phase==='stocks')return stocks();if(state.phase==='news')return newsScreen(false);if(state.phase==='finished')return resultScreen()}
function waiting(){shell(`<section class="reveal"><span class="step">أهلًا بك يا قبطان</span><h2>${state.me.name}</h2><p>تم تسجيلك. انتظر المضيف حتى يبدأ السباق.</p>${playerList()}<button class="btn ghost" onclick="clearSession()">مغادرة</button></section>`)}
function chooseShip(){if(state.me.ship)return shell(`<section class="reveal"><div class="mission-seal">✓</div><h2>تم اختيار باخرتك</h2><p>انتظر بقية القباطنة.</p><button class="btn secondary" onclick="openMyShip()">عرض باخرتي</button></section>`);shell(`<div class="stage-head"><div><span class="step">قرار سري</span><h2>اختر باخرتك</h2><p>اختيارك نهائي ولا يراه بقية القباطنة.</p></div></div><div class="grid ships">${state.ships.map((s,i)=>`<article class="card"><div class="ship-img s${i+1}"></div><div class="card-body"><h3>${s.name}</h3><div class="requirements">${Object.entries(s.need).map(([k,v])=>`<div class="req"><span>${R[k].i}</span>${v} ${R[k].n}</div>`).join('')}</div><button class="btn" onclick="chooseShipAction('${s.id}')">اختيار</button></div></article>`).join('')}</div>`)}
function auctionBoard(clickable){return `<div class="grid lands">${state.lands.map((name,index)=>{const offers=state.auction?.offers.filter(o=>o.landIndex===index)||[];return `<article class="card land ${selectedLand===index?'selected':''}" ${clickable?`onclick="selectLand(${index})"`:''}><span class="step">قطعة ${index+1}</span><h3>${name}</h3><div class="land-bidders">${offers.length?offers.map(o=>`<span>${o.name}<b>${fmt(o.amount)}</b></span>`).join(''):'<small>لا عروض</small>'}</div></article>`}).join('')}</div>`}
function playerAuction(){const mine=state.auction?.currentPlayerId===state.me.id;if(!mine)return shell(`<div class="stage-head"><div><span class="step">مزاد مباشر</span><h2>انتظر دورك</h2><p>${state.message}</p></div></div>${auctionBoard(false)}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="lands-bg"></div>`);shell(`<div class="stage-head"><div><span class="step">دورك الآن</span><h2>اختر أرضًا وضع عرضك</h2><p>العروض بمضاعفات 500 وتظهر للجميع.</p></div></div>${auctionBoard(true)}<div class="bid-panel"><div><small>قيمة عرضك</small><div class="bid-price" id="bidValue">${fmt(bidAmount)}</div></div><div class="bid-actions"><button class="btn secondary" onclick="changeBid(-500)">−500</button><button class="btn secondary" onclick="changeBid(500)">+500</button><button class="btn" onclick="placeBid()">تثبيت العرض</button></div></div><button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="lands-bg"></div>`)}
function chooseQuestion(){if(state.me.difficulty)return shell(`<section class="reveal"><h2>تم اختيار المستوى</h2><p>انتظر بقية القباطنة حتى تبدأ الأسئلة معًا.</p></section>`);shell(`<div class="stage-head"><div><span class="step">تحدي المعرفة</span><h2>اختر مستوى السؤال</h2><p>كل سؤال جديد ولا يتكرر داخل الغرفة.</p></div></div><div class="grid questions"><article class="card qcard easy" onclick="questionLevel('easy')"><h3>سهل</h3><div class="money">1,000</div></article><article class="card qcard medium" onclick="questionLevel('medium')"><h3>متوسط</h3><div class="money">3,000</div></article><article class="card qcard hard" onclick="questionLevel('hard')"><h3>صعب</h3><div class="money">5,000</div></article></div>`)}
function answerQuestion(){if(state.me.answered)return shell(`<section class="reveal"><div class="mission-seal">✓</div><h2>تم تسجيل إجابتك</h2><p>انتظر بقية القباطنة.</p></section>`);const q=state.me.question;if(!q)return shell('<section class="reveal"><h2>جارٍ تجهيز السؤال…</h2></section>');shell(`<section class="question-box"><span class="step">الجائزة ${fmt(state.me.prize)}</span><h3>${q.q}</h3><div class="answers">${q.a.map((a,i)=>`<button class="answer" onclick="sendAnswer(${i})">${a}</button>`).join('')}</div></section>`)}

function resourceBar(){return `<div class="resource-bar"><div>💰 <b>${fmt(state.me.cash)}</b></div>${Object.keys(R).map(k=>`<div>${R[k].i} <b>${state.me.res[k]}</b></div>`).join('')}</div>`}
function market(){const others=state.players.filter(p=>p.id!==state.me.id);shell(`${resourceBar()}<div class="stage-head"><div><span class="step">السوق العالمي</span><h2>البيع والشراء والمقايضة</h2><p>كل العمليات تتحقق منها اللعبة على الخادم.</p></div></div><div class="market-resource-grid">${Object.keys(R).map(k=>`<article class="market-resource"><i>${R[k].i}</i><h3>${R[k].n}</h3><b>${fmt(state.prices[k])}</b><small>للشراء • البيع ${fmt(Math.floor(state.prices[k]*.78))}</small><div><button class="mini" onclick="openMarketOrder('${k}','buy')">شراء</button><button class="mini sell" onclick="openMarketOrder('${k}','sell')">بيع</button></div></article>`).join('')}</div><section class="captains-council"><div class="council-head"><div><span class="step">مجلس القباطنة</span><h2>المقايضات المباشرة</h2></div><button class="btn propose-btn" onclick="openTrade()">＋ قدّم عرضك</button></div>${tradeInbox()}${state.me.outgoingTrades.length?`<h3>عروضك المرسلة</h3>${state.me.outgoingTrades.map(t=>`<div class="trade-line">إلى ${state.players.find(p=>p.id===t.to)?.name}: ${t.giveQty} ${R[t.give].i} مقابل ${t.wantQty} ${R[t.want].i}<small>بانتظار الرد</small></div>`).join('')}`:''}</section><button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="market-bg"></div>`)}
function tradeInbox(){if(!state.me.incomingTrades.length)return '<p class="muted">لا توجد عروض واردة الآن.</p>';return state.me.incomingTrades.map(t=>`<div class="trade-line"><b>${t.fromName}</b><span>يعطيك ${t.giveQty} ${R[t.give].i} مقابل ${t.wantQty} ${R[t.want].i}</span><div><button class="mini" onclick="respondTrade('${t.id}',true)">قبول</button><button class="mini sell" onclick="respondTrade('${t.id}',false)">رفض</button></div></div>`).join('')}
function stocks(){shell(`${resourceBar()}<div class="stage-head"><div><span class="step">بورصة أرض النفط</span><h2>سوق الأسهم</h2><p>تابع التغير ونفذ أوامرك قبل إغلاق السوق.</p></div></div>${stockBoard(false)}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="market-bg"></div>`)}
function stockBoard(host){return `<div class="stock-grid">${Object.keys(R).map((k,i)=>{const c=state.lastChanges[k],up=c>=0;return `<article class="stock-card ${up?'stock-up':'stock-down'}"><div class="stock-title"><div class="stock-icon">${R[k].i}</div><div><small>شركة ${R[k].n}</small><h3>سهم ${R[k].n}</h3></div></div><div class="stock-price"><b>${fmt(state.stockPrices[k])}</b><span>ريال للسهم</span></div><div class="stock-change ${up?'up':'down'}"><b>${up?'▲ مرتفع':'▼ منخفض'} ${Math.abs(c).toFixed(1)}%</b></div>${!host?`<div class="stock-owned">تملك <b>${state.me.stocks[k]}</b> سهم</div><div class="stock-actions"><button class="mini" onclick="openStockOrder('${k}','buy')">شراء</button><button class="mini sell" onclick="openStockOrder('${k}','sell')">بيع</button></div>`:''}</article>`}).join('')}</div>`}
function newsScreen(host){const items=state.news.length?state.news:['الأسواق هادئة والقباطنة يترقبون الجولة القادمة.'];shell(`<section class="news-card"><span class="breaking">نشرة أرض النفط</span><div class="on-air">● على الهواء</div><div class="headline">${items[items.length-1]}</div><div class="ticker">${items.join(' • ')}</div><div class="market-summary">${Object.keys(R).map(k=>`<div class="resource"><i>${R[k].i}</i><b class="change ${state.lastChanges[k]>=0?'up':'down'}">${state.lastChanges[k]>=0?'▲':'▼'} ${Math.abs(state.lastChanges[k]).toFixed(1)}%</b><small>${R[k].n}</small></div>`).join('')}</div>${host?'<button class="btn" onclick="advance()">إنهاء النشرة</button>':'<p>انتظر المضيف أو انتهاء المؤقت…</p>'}</section>`,`<div class="news-bg"></div>`)}
function resultScreen(){const winner=state.players.find(p=>p.id===state.winner);shell(`<section class="result"><span class="step">انتهى السباق</span><h1>${winner?.name||'القبطان الفائز'}</h1><p>أكمل حمولة باخرته أولًا وأصبح سيد أرض النفط.</p><div class="ship-sail"></div>${state.host?'<button class="btn" onclick="clearSession()">إنشاء لعبة جديدة</button>':'<button class="btn" onclick="clearSession()">العودة للرئيسية</button>'}</section>`,`<div class="news-bg"></div>`)}

async function startGame(){try{state=await api('start');render()}catch(e){toast(e.message)}}
async function advance(){try{state=await api('advance');render()}catch(e){toast(e.message)}}
async function chooseShipAction(ship){try{state=await api('chooseShip',{ship});render()}catch(e){toast(e.message)}}
function selectLand(index){selectedLand=index;render()}
function changeBid(delta){bidAmount=Math.max(500,Math.min(state.me.cash,bidAmount+delta));$('#bidValue').textContent=fmt(bidAmount)}
async function placeBid(){if(selectedLand===null)return toast('اختر أرضًا');try{state=await api('bid',{landIndex:selectedLand,amount:bidAmount});selectedLand=null;bidAmount=500;render()}catch(e){toast(e.message)}}
async function questionLevel(level){try{state=await api('chooseQuestion',{level});render()}catch(e){toast(e.message)}}
async function sendAnswer(index){try{state=await api('answer',{index});render()}catch(e){toast(e.message)}}

function openModal(html){const modal=$('#modal');modal.innerHTML=`<div class="modal">${html}</div>`;modal.classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function qtyTicket(title,max,confirm){openModal(`<button class="modal-close" onclick="closeModal()">×</button><h2>${title}</h2><label class="qty-label">الكمية<input id="modalQty" type="number" min="1" max="${max}" value="1"></label><button class="btn order-confirm" onclick="${confirm}">إبرام الصفقة</button>`)}
function openMarketOrder(resource,side){const max=side==='buy'?Math.floor(state.me.cash/state.prices[resource]):state.me.res[resource];if(max<1)return toast('لا توجد كمية متاحة');qtyTicket(`${side==='buy'?'شراء':'بيع'} ${R[resource].n}`,max,`marketOrder('${resource}','${side}')`)}
async function marketOrder(resource,side){try{const quantity=Number($('#modalQty').value);state=await api('marketOrder',{resource,side,quantity});closeModal();render();toast('تم إبرام الصفقة')}catch(e){toast(e.message)}}
function openStockOrder(resource,side){const max=side==='buy'?Math.floor(state.me.cash/state.stockPrices[resource]):state.me.stocks[resource];if(max<1)return toast('لا توجد كمية متاحة');qtyTicket(`${side==='buy'?'شراء':'بيع'} سهم ${R[resource].n}`,max,`stockOrder('${resource}','${side}')`)}
async function stockOrder(resource,side){try{const quantity=Number($('#modalQty').value);state=await api('stockOrder',{resource,side,quantity});closeModal();render();toast('تم تنفيذ أمر الأسهم')}catch(e){toast(e.message)}}
function openTrade(){const players=state.players.filter(p=>p.id!==state.me.id),opts=Object.keys(R).map(k=>`<option value="${k}">${R[k].i} ${R[k].n}</option>`).join('');openModal(`<button class="modal-close" onclick="closeModal()">×</button><h2>قدّم عرض مقايضة</h2><label class="qty-label">إلى<select id="tradeTo">${players.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></label><div class="offer-builder"><div><label>أعطي</label><select id="tradeGive">${opts}</select><input id="tradeGiveQty" type="number" min="1" value="1"></div><div class="swap-mark">⇄</div><div><label>أطلب</label><select id="tradeWant">${opts}</select><input id="tradeWantQty" type="number" min="1" value="1"></div></div><button class="btn order-confirm" onclick="sendTrade()">إرسال العرض</button>`)}
async function sendTrade(){try{state=await api('createTrade',{to:$('#tradeTo').value,give:$('#tradeGive').value,giveQty:Number($('#tradeGiveQty').value),want:$('#tradeWant').value,wantQty:Number($('#tradeWantQty').value)});closeModal();render();toast('تم إرسال العرض')}catch(e){toast(e.message)}}
async function respondTrade(tradeId,accept){try{state=await api('respondTrade',{tradeId,accept});render();toast(accept?'تمت الصفقة':'رُفض العرض')}catch(e){toast(e.message)}}
function openMyShip(){const ship=state.ships.find(s=>s.id===state.me.ship);if(!ship)return;openModal(`<button class="modal-close" onclick="closeModal()">×</button><span class="step">باخرتي</span><h2>${ship.name}</h2>${Object.entries(ship.need).map(([k,n])=>{const have=state.me.res[k],pct=Math.min(100,Math.round(have/n*100));return `<div class="cargo-line"><div><b>${R[k].i} ${R[k].n}</b><span>${have} من ${n} — المتبقي ${Math.max(0,n-have)}</span></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join('')}<div class="reward"><b>المهمة السرية: ${state.me.mission.title}</b><br>${state.me.mission.text}<br>${state.me.missionDone?'✅ تم الإنجاز':'المكافأة: '+state.me.mission.reward}</div>`)}

if(session){refresh().then(startPolling)}else home();
