const $ = selector => document.querySelector(selector), app = $('#app');
const R = { oil:{n:'النفط',i:'🛢️'}, gas:{n:'الغاز',i:'🔥'}, gold:{n:'الذهب',i:'🪙'}, iron:{n:'الحديد',i:'⚙️'} };
const PHASES = { lobby:'اللوبي', ship:'اختيار الباخرة', auction:'مزاد الأراضي', auctionResult:'نتائج المزاد', mission:'المهمة السرية', questionSelect:'اختيار السؤال', question:'الأسئلة', answerReveal:'نتيجة الإجابة', market:'السوق والمقايضات', stocks:'سوق الأسهم', news:'نشرة الأخبار', finished:'النتيجة' };
const INTRO = [
  { image:'ships.png', title:'اختر باخرتك', text:'كل قبطان يبدأ بـ 5,000 ريال ويختار باخرة واحدة. للفوز عليك جمع جميع الموارد المطلوبة لباخرتك.' },
  { image:'lands.png', title:'مزاد سري على ست أراضٍ', text:'أمام الجميع 30 ثانية. وزّع عروضك على أي عدد من الأراضي، ويُخصم كل عرض فور تأكيده حتى لو لم يرسُ المزاد عليك.' },
  { image:'lands.png', title:'اكتشف موارد أرضك', text:'بعد رسو المزاد تحصل من أرضك على نفط وغاز وذهب وحديد بكميات مخفية، ثم يقرأ كل قبطان مهمته السرية.' },
  { image:'market.png', title:'الأسئلة ثم السوق', text:'يختار الجميع مستوى السؤال ويجيبون في الوقت نفسه. لا يفتح السوق حتى ينتهي آخر قبطان، ثم تستطيع البيع والشراء والمقايضة.' },
  { image:'news.png', title:'الأسهم والنشرة والفوز', text:'بعد السوق تفتح البورصة. عندما تكتمل باخرتك اضغط «إرسال الباخرة» لتوقف اللعبة فورًا وتُعلن فائزًا.' }
];

const IS_DEMO = location.pathname.endsWith('/demo.html');
const DEMO_DIFFICULTY = new URLSearchParams(location.search).get('difficulty') === 'hard' ? 'hard' : 'easy';
const SESSION_KEY = IS_DEMO ? `oil-land-demo-${DEMO_DIFFICULTY}-session` : 'oil-land-session';
const QUESTION_HISTORY_KEY = IS_DEMO ? `oil-land-demo-${DEMO_DIFFICULTY}-used-questions-v1` : 'oil-land-used-questions-v1';
let session = JSON.parse(localStorage.getItem(SESSION_KEY) || 'null');
let state = null, poller = null, clock = null, lastRender = '', bidDraft = {};
const fmt = number => new Intl.NumberFormat('ar-SA').format(number || 0);

function toast(text){const element=$('#toast');element.textContent=text;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),2600)}
async function api(action, extra={}){const payload={action,...extra};if(session){payload.code=session.code;payload.token=session.token}const response=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'تعذر تنفيذ الطلب');if(['create','join','demo'].includes(action))return data;return data.state||data}
function saveSession(value){session=value;localStorage.setItem(SESSION_KEY,JSON.stringify(value))}
function clearSession(){session=null;state=null;localStorage.removeItem(SESSION_KEY);clearInterval(poller);clearInterval(clock);if(IS_DEMO){location.href=`/demo.html${DEMO_DIFFICULTY==='hard'?'?difficulty=hard':''}`;return}history.replaceState({},'', '/');home()}

async function resumeSession(){
  if(!session)return home();
  try{
    app.innerHTML=`<div class="screen direct-start"><div class="noise"></div><div class="waiting-radar"></div><h2>جارٍ العودة إلى الغرفة ${session.code}…</h2></div>`;
    await refresh();
    if(state)startPolling();
  }catch(error){toast(error.message);clearSession()}
}

function home(){
  const code=new URLSearchParams(location.search).get('room')?.toUpperCase();
  app.innerHTML=`<div class="screen oil-home"><div class="noise"></div><div class="oil-home-glow"></div><main class="oil-home-layout"><section class="oil-home-brand"><span class="home-kicker">لعبة الاقتصاد والمغامرة</span><h1>أرض<br><b>النفط</b></h1><p>اجمع الموارد، نافس في المزادات، سيطر على السوق، وأرسل باخرتك قبل الجميع.</p><div class="home-features"><span>🛢️ مزادات</span><span>🚢 بواخر</span><span>📈 أسهم</span><span>🧠 أسئلة</span></div></section><section class="home-command"><div class="home-command-head"><small>${code?'دعوة إلى غرفة':'ميناء الانطلاق'}</small><h2>${code?`الغرفة ${code}`:'اختر وجهتك'}</h2></div>${code?`<div class="direct-join"><div class="room-chip">رمز الغرفة ${code}</div><label>اسم القبطان<input id="captainName" class="input" maxlength="20" placeholder="اكتب اسمك هنا"></label><button class="home-action primary" onclick="joinRoom('${code}')"><i>⚓</i><span><b>دخول اللعبة</b><small>الانضمام إلى القباطنة</small></span><em>←</em></button><button class="home-action quiet" onclick="history.replaceState({},'', '/');home()"><i>⌂</i><span><b>العودة للواجهة</b></span></button></div>`:`<div class="home-action-list">${session?`<button class="home-action primary" onclick="resumeSession()"><i>↻</i><span><b>متابعة الغرفة السابقة</b><small>الغرفة ${session.code}</small></span><em>←</em></button>`:''}<button class="home-action ${session?'':'primary'}" onclick="createRoom()"><i>＋</i><span><b>غرفة جديدة</b><small>إنشاء غرفة وعرض الباركود</small></span><em>←</em></button><button class="home-action" onclick="showJoin()"><i>⚓</i><span><b>دخول اللعبة</b><small>لديك رمز غرفة جاهز</small></span><em>←</em></button><button class="home-action" onclick="showQuickGuide()"><i>؟</i><span><b>كيفية اللعب بسرعة</b><small>شرح مختصر في أقل من دقيقة</small></span><em>←</em></button>${session?`<button class="home-action quiet" onclick="clearSession()"><i>×</i><span><b>نسيان الغرفة السابقة</b></span></button>`:''}</div><div id="joinArea"></div>`}</section></main><footer class="oil-home-footer"><span>من 2 إلى 10 قباطنة</span><span>كل لاعب من جواله</span><span>المضيف على شاشة العرض</span></footer></div>`;
}
function showJoin(){$('#joinArea').innerHTML=`<div class="join-box home-join-box"><button class="join-close" onclick="$('#joinArea').innerHTML=''">×</button><h3>دخول غرفة موجودة</h3><label>رمز الغرفة<input id="roomCode" class="input" maxlength="5" placeholder="مثال: A7B3C"></label><label>اسم القبطان<input id="captainName" class="input" maxlength="20" placeholder="اكتب اسمك"></label><button class="btn" onclick="joinRoom()">دخول اللعبة</button></div>`;$('#roomCode')?.focus()}
function showQuickGuide(){openModal(`<button class="modal-close" onclick="closeModal()">×</button><span class="step">شرح سريع</span><h2>كيف تلعب أرض النفط؟</h2><div class="quick-guide"><div><i>1</i><span><b>اختر باخرتك</b><small>لكل باخرة احتياجات مختلفة، وأول من يجمعها ويرسل باخرته يفوز.</small></span></div><div><i>2</i><span><b>زايد على الأراضي</b><small>أمامك 30 ثانية. وزّع عروضك بحذر؛ قيمة العرض تُخصم حتى لو خسرت.</small></span></div><div><i>3</i><span><b>اكشف الموارد والمهمة</b><small>الأرض تعطيك موارد عشوائية، والمهمة السرية تمنحك مكافأة وصندوقًا.</small></span></div><div><i>4</i><span><b>اربح من الأسئلة والسوق</b><small>أجب لتحصل على المال، ثم اشترِ وبِع وقايض واستثمر في الأسهم.</small></span></div><div><i>5</i><span><b>أرسل الباخرة</b><small>عند اكتمال جميع الموارد افتح «باخرتي» واضغط إرسال الباخرة للفوز فورًا.</small></span></div></div><button class="btn order-confirm" onclick="closeModal()">فهمت — جاهز للعب</button>`)}
function showIntro(index,viewOnly=false){const slide=INTRO[index];app.innerHTML=`<div class="screen intro-screen"><div class="noise"></div><section class="intro-card"><div class="intro-picture" style="background-image:linear-gradient(180deg,transparent,#07161ddd),url('${slide.image}')"></div><div class="intro-copy"><span class="step">شرح اللعبة ${index+1} من ${INTRO.length}</span><h1>${slide.title}</h1><p>${slide.text}</p><div class="intro-dots">${INTRO.map((_,i)=>`<i class="${i===index?'active':''}"></i>`).join('')}</div><div class="intro-actions">${index?`<button class="btn ghost" onclick="showIntro(${index-1},${viewOnly})">السابق</button>`:'<button class="btn ghost" onclick="home()">رجوع</button>'}${index<INTRO.length-1?`<button class="btn" onclick="showIntro(${index+1},${viewOnly})">التالي</button>`:viewOnly?'<button class="btn" onclick="home()">فهمت</button>':'<button class="btn" onclick="createRoom()">إنشاء الغرفة</button>'}</div></div></section></div>`}
async function createRoom(){try{const used=JSON.parse(localStorage.getItem(QUESTION_HISTORY_KEY)||'[]');const data=await api('create',{usedQuestionIds:used});saveSession({code:data.code,token:data.token,role:'host'});state=data.state;startPolling();render()}catch(error){toast(error.message)}}
async function createDemo(){try{app.innerHTML=`<div class="screen direct-start"><div class="noise"></div><div class="waiting-radar"></div><h2>جارٍ تجهيز ثلاثة قباطنة آليين — المستوى ${DEMO_DIFFICULTY==='hard'?'الصعب':'السهل'}…</h2></div>`;const used=JSON.parse(localStorage.getItem(QUESTION_HISTORY_KEY)||'[]');const data=await api('demo',{usedQuestionIds:used,difficulty:DEMO_DIFFICULTY});saveSession({code:data.code,token:data.token,role:'player',demo:true,difficulty:DEMO_DIFFICULTY});state=data.state;startPolling();render()}catch(error){toast(error.message)}}
async function joinRoom(forced){try{const code=(forced||$('#roomCode')?.value||'').trim().toUpperCase(),name=$('#captainName').value.trim();if(!code||!name)return toast('اكتب الرمز واسم القبطان');session={code,token:'',role:'player'};const data=await api('join',{name});saveSession({code,token:data.token,role:'player'});state=data.state;startPolling();render()}catch(error){session=null;toast(error.message)}}
async function refresh(){if(!session)return;try{const next=await api('state');if(next.usedQuestionIds)localStorage.setItem(QUESTION_HISTORY_KEY,JSON.stringify(next.usedQuestionIds));const signature=JSON.stringify(next);state=next;if(signature!==lastRender){lastRender=signature;render()}updateClock()}catch(error){toast(error.message);if(/غير موجودة|رمز/.test(error.message))clearSession()}}
function startPolling(){clearInterval(poller);poller=setInterval(refresh,1000);clearInterval(clock);clock=setInterval(updateClock,250)}
function updateClock(){const element=$('#globalClock');if(!element||!state)return;const left=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));element.textContent=state.deadline?left:'--';element.parentElement?.classList.toggle('danger',left<=10&&left>0)}

function gameHeader(){return `<div class="topbar"><div class="logo">أرض النفط <small>#${state.code}</small></div><div class="stats"><div class="pill">${PHASES[state.phase]}</div><div class="pill">${state.difficulty==='hard'?'🔥 صعب':'🌿 سهل'}</div><div class="pill">الجولة <b>${state.round}</b></div>${state.me?`<div class="pill">الرصيد <b>${fmt(state.me.cash)}</b></div>`:''}<div class="clock-ring"><small>الوقت</small><b id="globalClock">--</b></div></div></div>`}
function shell(content,bg=''){app.innerHTML=`<div class="screen online-screen"><div class="noise"></div>${bg}${gameHeader()}<main class="main">${content}</main></div>`;updateClock()}
function progressStatus(player){if(state.phase==='ship')return player.shipChosen?'اختار الباخرة':'يختار الآن';if(state.phase==='auction')return 'يضع عروضه سرًا';if(state.phase==='auctionResult')return player.auctionSeen?'شاهد النتائج':`${player.landCount||0} أراضٍ`;if(state.phase==='mission')return player.missionRead?'قرأ المهمة':'يقرأ المهمة';if(state.phase==='questionSelect')return player.questionChosen?'اختار السؤال':'يختار المستوى';if(state.phase==='question')return player.answered?'أجاب':'يجيب الآن';if(['market','stocks'].includes(state.phase))return player.stageDone?'انتهى':'ما زال يعمل';return player.connected?'متصل':'غير متصل'}
function playerList(){return `<div class="online-players">${state.players.map(player=>`<div class="online-player ${player.connected?'':'offline'} ${progressStatus(player).includes('انته')||progressStatus(player).includes('اختار')||progressStatus(player).includes('قرأ')||progressStatus(player).includes('أجاب')||progressStatus(player).includes('امتلك')?'done':''}"><i>${player.bot?'🤖':player.hasLand?'⛽':player.shipChosen?'🚢':'⚓'}</i><b>${player.name}</b><small>${player.bot?'قبطان آلي • ':''}${progressStatus(player)}</small></div>`).join('')}</div>`}
function waitingCard(title,text){return `<section class="reveal wait-card"><div class="waiting-radar"></div><span class="step">الجميع يتحرك معًا</span><h2>${title}</h2><p>${text}</p>${playerList()}</section>`}

function render(){if(!state)return home();if(state.host)renderHost();else renderPlayer()}
function renderHost(){
  if(state.phase==='lobby')return hostLobby();
  if(state.phase==='auction')return hostAuction();
  if(state.phase==='auctionResult')return auctionResult(true);
  if(state.phase==='news')return newsScreen(true);
  if(state.phase==='finished')return resultScreen();
  const extra=state.phase==='market'?marketBoard():state.phase==='stocks'?stockBoard(true):'';
  shell(`<section class="host-stage"><span class="step">شاشة العرض</span><h1>${PHASES[state.phase]}</h1><p>${state.message}</p>${playerList()}${extra}<button class="btn host-next" onclick="advance()">إنهاء الوقت والانتقال</button></section>`,['market','stocks'].includes(state.phase)?'<div class="market-bg"></div>':'');
}
function hostLobby(){const joinUrl=`${location.origin}/?room=${state.code}`;shell(`<section class="lobby-layout"><div><span class="step">غرفة جديدة</span><h1>امسح الباركود وانضم</h1><div class="code-big">${state.code}</div><p>${state.players.length} قباطنة متصلون</p><section class="difficulty-setting"><div><span class="step">إعداد اللعبة</span><h3>اختر مستوى الصعوبة</h3></div><button class="difficulty-option ${state.difficulty==='easy'?'selected':''}" onclick="setDifficulty('easy')"><i>🌿</i><span><b>سهل</b><small>متطلبات البواخر الأساسية</small></span></button><button class="difficulty-option hard ${state.difficulty==='hard'?'selected':''}" onclick="setDifficulty('hard')"><i>🔥</i><span><b>صعب</b><small>متطلبات جميع البواخر ×2</small></span></button></section>${playerList()}<button class="btn" ${state.players.length<2?'disabled':''} onclick="startGame()">ابدأ اللعبة للجميع</button><button class="btn ghost" onclick="clearSession()">إغلاق الغرفة</button></div><div class="qr-card"><img src="/api/qr?text=${encodeURIComponent(joinUrl)}" alt="باركود الدخول"><small>${joinUrl}</small></div></section>`,`<div class="lands-bg"></div>`)}
function landOffers(index){return state.auction.offers.filter(offer=>offer.landIndex===index)}
function auctionGrid(host=false){return `<div class="simultaneous-auction">${state.auction.lands.map((land,index)=>{const mine=state.auction.offers.find(offer=>offer.landIndex===index&&offer.playerId===state.me?.id);const offers=landOffers(index);const amount=bidDraft[index]||500;return `<article class="auction-land ${mine?'bid-locked':''}"><div class="land-no">${index+1}</div><h3>${land.name}</h3><p>${land.description}</p><div class="sealed-count">🔒 ${offers.length} عروض مؤكدة</div>${host?'':mine?`<div class="my-sealed">عرضك المؤكد: <b>${fmt(mine.amount)}</b></div>`:`<div class="land-bid-controls"><button onclick="changeLandBid(${index},-500)">−</button><b id="landBid${index}">${fmt(amount)}</b><button onclick="changeLandBid(${index},500)">＋</button></div><button class="btn bid-confirm" onclick="placeLandBid(${index})">تأكيد العرض وخصم المبلغ</button>`}</article>`}).join('')}</div>`}
function hostAuction(){shell(`<div class="stage-head"><div><span class="step">مزاد سري متزامن</span><h2>ست أراضٍ أمام الجميع لمدة 30 ثانية</h2><p>كل قبطان يوزع أمواله كما يريد. لا تظهر قيمة العروض إلا بعد انتهاء الوقت.</p></div></div>${auctionGrid(true)}${playerList()}<button class="btn host-next" onclick="advance()">إغلاق المزاد وكشف النتائج</button>`,`<div class="lands-bg"></div>`)}
function marketBoard(){return `<div class="market-public">${Object.keys(R).map(key=>{const change=state.lastChanges[key],up=change>=0;return `<div><span>${R[key].i} ${R[key].n}</span><b>${fmt(state.prices[key])}</b><small class="market-trend ${up?'up':'down'}">${up?'▲ غلا':'▼ رخص'} ${Math.abs(change).toFixed(1)}%</small></div>`}).join('')}</div>`}

function renderPlayer(){if(state.phase==='lobby')return waiting();if(state.phase==='ship')return chooseShip();if(state.phase==='auction')return playerAuction();if(state.phase==='auctionResult')return auctionResult(false);if(state.phase==='mission')return secretMission();if(state.phase==='questionSelect')return chooseQuestion();if(['question','answerReveal'].includes(state.phase))return answerQuestion();if(state.phase==='market')return market();if(state.phase==='stocks')return stocks();if(state.phase==='news')return newsScreen(false);if(state.phase==='finished')return resultScreen()}
function waiting(){shell(waitingCard(`أهلًا بك يا ${state.me.name}`,'تم تسجيلك. انتظر المضيف حتى يبدأ السباق.'))}
function chooseShip(){if(state.me.ship)return shell(waitingCard('تم اختيار باخرتك','لن يبدأ المزاد حتى يختار جميع القباطنة.'));shell(`<div class="stage-head"><div><span class="step">${state.difficulty==='hard'?'المستوى الصعب — المتطلبات مضاعفة':'المستوى السهل'}</span><h2>اختر باخرتك</h2><p>اختيارك نهائي، والفوز بإكمال جميع احتياجاتها.</p></div></div><div class="grid ships">${state.ships.map((ship,index)=>`<article class="card"><div class="ship-img s${index+1}"></div><div class="card-body"><h3>${ship.name}</h3><div class="requirements">${Object.entries(ship.need).map(([key,value])=>`<div class="req"><span>${R[key].i}</span>${value} ${R[key].n}</div>`).join('')}</div><button class="btn" onclick="chooseShipAction('${ship.id}')">اختيار هذه الباخرة</button></div></article>`).join('')}</div>`)}
function playerAuction(){
  shell(`${resourceBar()}<div class="stage-head"><div><span class="step">30 ثانية فقط</span><h2>وزّع عروضك على الأراضي</h2><p>تستطيع شراء أكثر من أرض. كل عرض تؤكده يُخصم فورًا، ولن يعود إليك إذا خسرت المزاد.</p></div></div>${auctionGrid(false)}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="lands-bg"></div>`);
}
function auctionResult(host){const results=state.auction.results;const mine=host?[]:results.filter(item=>item.playerId===state.me.id);const won=results.filter(item=>!item.skipped);const summary=host?`<div class="auction-winners"><h3>نتائج الأراضي</h3>${results.map(item=>item.skipped?`<div><span>${item.land}</span><b>لم تُشترَ</b><small>بلا عروض</small></div>`:`<div><span>${item.land}</span><b>${item.name}</b><small>${fmt(item.amount)} ريال</small></div>`).join('')}</div>`:mine.length?`<section class="loot-reveal"><span class="step">مبروك يا ${state.me.name}</span><h2>فزت بـ ${mine.length} ${mine.length===1?'أرض':'أراضٍ'}</h2>${mine.map(item=>`<article><h3>${item.land}</h3><small>العرض الفائز ${fmt(item.amount)} ريال</small><div class="loot-row">${Object.keys(R).map(key=>`<div>${R[key].i}<b>+${item.loot[key]}</b><span>${R[key].n}</span></div>`).join('')}</div></article>`).join('')}</section>`:`<section class="loot-reveal empty-loot"><span class="step">انتهى المزاد</span><h2>لم تفز بأي أرض هذه الجولة</h2><p>العروض التي دفعتها لا تُسترد، ويمكنك التعويض في الأسئلة والسوق.</p></section>`;shell(`${summary}${playerList()}${host?'<button class="btn host-next" onclick="advance()">الانتقال للمهمات</button>':state.me.auctionSeen?'<p class="muted result-wait">شاهدت النتائج — ننتظر بقية القباطنة.</p>':'<button class="btn result-seen" onclick="markAuctionSeen()">شاهدت النتائج</button>'}`,`<div class="lands-bg"></div>`)}
function secretMission(){if(state.me.missionRead)return shell(waitingCard('تمت قراءة مهمتك','تبدأ الأسئلة عندما يضغط جميع القباطنة «قرأتها».'));const mission=state.me.mission;shell(`<section class="mission-reveal"><div class="mission-seal">!</div><span class="step">سري للغاية</span><h1>${mission.title}</h1><p>${mission.text}</p><div class="mission-reward">المكافأة: <b>${mission.reward}</b></div><button class="btn" onclick="markMissionRead()">قرأتها ومستعد</button></section>`)}
function chooseQuestion(){if(state.me.difficulty)return shell(waitingCard('تم اختيار سؤالك','لن تبدأ الأسئلة حتى يختار الجميع.'));shell(`<div class="stage-head"><div><span class="step">تحدي المعرفة</span><h2>اختر مستوى السؤال</h2><p>يبدأ عداد الأسئلة للجميع بعد آخر اختيار.</p></div></div><div class="grid questions"><article class="card qcard easy" onclick="questionLevel('easy')"><h3>سهل</h3><div class="money">1,000</div></article><article class="card qcard medium" onclick="questionLevel('medium')"><h3>متوسط</h3><div class="money">3,000</div></article><article class="card qcard hard" onclick="questionLevel('hard')"><h3>صعب</h3><div class="money">5,000</div></article></div>`)}
function answerQuestion(){if(state.me.answered){const correct=state.me.answerCorrect;return shell(`<section class="answer-reveal ${correct?'correct':'wrong'}"><div class="answer-burst"></div><div class="answer-symbol">${correct?'✓':'×'}</div><span class="step">نتيجة إجابتك</span><h1>${correct?'إجابة صحيحة':'إجابة خاطئة'}</h1>${correct?`<p>أحسنت! أضيفت جائزة قدرها <b>${fmt(state.me.prize)} ريال</b> إلى رصيدك.</p>`:`<p>الإجابة الصحيحة هي:</p><div class="correct-answer">${state.me.correctAnswer||'انتهى الوقت'}</div>`}<small>${state.phase==='answerReveal'?'ننتقل للمرحلة التالية بعد لحظات…':'بانتظار إجابات بقية القباطنة…'}</small></section>`)}const question=state.me.question;if(!question)return shell(waitingCard('جارٍ تجهيز السؤال','لحظات ويبدأ التحدي للجميع.'));shell(`<section class="question-box"><span class="step">الجائزة ${fmt(state.me.prize)}</span><h3>${question.q}</h3><div class="answers">${question.a.map((answer,index)=>`<button class="answer" onclick="sendAnswer(${index})">${answer}</button>`).join('')}</div></section>`)}

function resourceBar(){return `<div class="resource-bar"><div>💰 <b>${fmt(state.me.cash)}</b></div>${Object.keys(R).map(key=>`<div>${R[key].i} <b>${state.me.res[key]}</b></div>`).join('')}</div>`}
function phaseFinishButton(){return `<section class="finish-strip"><div><b>خلصت؟</b><span>بعد الضغط تنتظر بقية القباطنة ولا يمكنك تنفيذ عمليات جديدة.</span></div><button class="btn" onclick="finishPhase()">انتهيت من هذه المرحلة</button></section>`}
function market(){if(state.me.stageDone)return shell(`${resourceBar()}${waitingCard('انتهيت من السوق','ننتقل إلى الأسهم عند انتهاء الجميع أو انتهاء الوقت.')}`,'<div class="market-bg"></div>');shell(`${resourceBar()}<div class="stage-head"><div><span class="step">السوق للجميع</span><h2>بيع، اشترِ وقايض</h2><p>راقب ما غلا وما رخص، ثم نفّذ صفقاتك قبل انتهاء الوقت.</p></div></div><div class="market-resource-grid">${Object.keys(R).map(key=>{const change=state.lastChanges[key],up=change>=0;return `<article class="market-resource"><i>${R[key].i}</i><h3>${R[key].n}</h3><div class="market-trend ${up?'up':'down'}">${up?'▲ غلا':'▼ رخص'} ${Math.abs(change).toFixed(1)}%</div><b>${fmt(state.prices[key])}</b><small>للشراء • البيع ${fmt(Math.floor(state.prices[key]*.78))}</small><div><button class="mini" onclick="openMarketOrder('${key}','buy')">شراء</button><button class="mini sell" onclick="openMarketOrder('${key}','sell')">بيع</button></div></article>`}).join('')}</div><article class="mystery-box-card"><div class="mystery-box">?</div><div><span class="step">مخاطرة السوق</span><h2>الصندوق العشوائي</h2><p>قد تجد أموالًا أو موارد كثيرة، وقد تفتحه ولا تجد شيئًا.</p></div><div><b>2,000 ريال</b><button class="btn" onclick="buyMysteryBox()">شراء وفتح الصندوق</button></div></article><section class="captains-council"><div class="council-head"><div><span class="step">مجلس القباطنة</span><h2>المقايضات المباشرة</h2></div><button class="btn propose-btn" onclick="openTrade()">＋ قدّم عرضك</button></div>${tradeInbox()}${state.me.outgoingTrades.length?`<h3>عروضك المرسلة</h3>${state.me.outgoingTrades.map(trade=>`<div class="trade-line">إلى ${state.players.find(player=>player.id===trade.to)?.name}: ${trade.giveQty} ${R[trade.give].i} مقابل ${trade.wantQty} ${R[trade.want].i}<small>بانتظار الرد</small></div>`).join('')}`:''}</section>${phaseFinishButton()}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="market-bg"></div>`)}
function tradeInbox(){if(!state.me.incomingTrades.length)return '<p class="muted">لا توجد عروض واردة الآن.</p>';return state.me.incomingTrades.map(trade=>`<div class="trade-line"><b>${trade.fromName}</b><span>يعطيك ${trade.giveQty} ${R[trade.give].i} مقابل ${trade.wantQty} ${R[trade.want].i}</span><div><button class="mini" onclick="respondTrade('${trade.id}',true)">قبول</button><button class="mini sell" onclick="respondTrade('${trade.id}',false)">رفض</button></div></div>`).join('')}
function stocks(){if(state.me.stageDone)return shell(`${resourceBar()}${waitingCard('انتهيت من الأسهم','تبدأ النشرة عند انتهاء الجميع أو انتهاء الوقت.')}`,'<div class="market-bg"></div>');shell(`${resourceBar()}<div class="stage-head"><div><span class="step">البورصة للجميع</span><h2>سوق الأسهم</h2><p>نفّذ استثماراتك ثم اضغط «انتهيت».</p></div></div>${stockBoard(false)}${phaseFinishButton()}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="market-bg"></div>`)}
function stockBoard(host){return `<div class="stock-grid">${Object.keys(R).map(key=>{const change=state.lastChanges[key],up=change>=0;return `<article class="stock-card ${up?'stock-up':'stock-down'}"><div class="stock-title"><div class="stock-icon">${R[key].i}</div><div><small>شركة ${R[key].n}</small><h3>سهم ${R[key].n}</h3></div></div><div class="stock-price"><b>${fmt(state.stockPrices[key])}</b><span>ريال للسهم</span></div><div class="stock-change ${up?'up':'down'}"><b>${up?'▲ مرتفع':'▼ منخفض'} ${Math.abs(change).toFixed(1)}%</b></div>${!host?`<div class="stock-owned">تملك <b>${state.me.stocks[key]}</b> سهم</div><div class="stock-actions"><button class="mini" onclick="openStockOrder('${key}','buy')">شراء</button><button class="mini sell" onclick="openStockOrder('${key}','sell')">بيع</button></div>`:''}</article>`}).join('')}</div>`}
function newsScreen(host){const items=state.news.length?state.news:['الأسواق هادئة والقباطنة يترقبون الجولة القادمة.'];shell(`<section class="news-card"><span class="breaking">نشرة أرض النفط</span><div class="on-air">● على الهواء</div><div class="headline">${items[items.length-1]}</div><div class="ticker">${items.join(' • ')}</div><div class="market-summary">${Object.keys(R).map(key=>`<div class="resource"><i>${R[key].i}</i><b class="change ${state.lastChanges[key]>=0?'up':'down'}">${state.lastChanges[key]>=0?'▲':'▼'} ${Math.abs(state.lastChanges[key]).toFixed(1)}%</b><small>${R[key].n}</small></div>`).join('')}</div>${host?'<button class="btn" onclick="advance()">بدء الجولة التالية</button>':'<p>الجولة التالية تبدأ للجميع بعد النشرة.</p>'}</section>`,`<div class="news-bg"></div>`)}
function resultScreen(){const winner=state.players.find(player=>player.id===state.winner),winning=state.finalStandings.find(player=>player.id===state.winner);shell(`<section class="winner-cinematic"><span class="step">أبحرت الباخرة أولًا</span><div class="winner-crown">⚓</div><h1>الفائز القبطان<br><b>${winner?.name||'القبطان الفائز'}</b></h1><p>${winning?.ship||'الباخرة'} اكتملت حمولتها وانطلقت من الميناء.</p><div class="ship-sail"></div>${winning?`<div class="winner-cargo">${Object.keys(R).map(key=>`<div>${R[key].i}<b>${winning.res[key]}</b><small>المطلوب ${winning.need[key]}</small></div>`).join('')}</div>`:''}</section><section class="final-progress"><h2>تقدم جميع القباطنة عند توقف اللعبة</h2>${state.finalStandings.map((player,index)=>`<article class="final-player ${player.id===state.winner?'champion':''}"><b>${index+1}. ${player.name}</b><span>${player.ship||''}</span><div class="progress"><i style="width:${player.progress}%"></i></div><strong>${player.progress}%</strong><div class="final-resources">${Object.keys(R).map(key=>`<small>${R[key].i} ${Math.min(player.res[key],player.need[key])}/${player.need[key]}</small>`).join('')}</div></article>`).join('')}<button class="btn" onclick="clearSession()">إنشاء لعبة جديدة</button></section>`,`<div class="news-bg"></div>`)}

async function startGame(){try{state=await api('start');render()}catch(error){toast(error.message)}}
async function setDifficulty(difficulty){try{state=await api('setDifficulty',{difficulty});render();toast(difficulty==='hard'?'تم اختيار المستوى الصعب':'تم اختيار المستوى السهل')}catch(error){toast(error.message)}}
async function advance(){try{state=await api('advance');render()}catch(error){toast(error.message)}}
async function chooseShipAction(ship){try{state=await api('chooseShip',{ship});render()}catch(error){toast(error.message)}}
function changeLandBid(index,delta){const current=bidDraft[index]||500;bidDraft[index]=Math.max(500,Math.min(state.me.cash,current+delta));$(`#landBid${index}`).textContent=fmt(bidDraft[index])}
async function placeLandBid(index){const amount=bidDraft[index]||500;if(!confirm(`سيُخصم ${fmt(amount)} ريال فورًا ولن يعود إذا خسرت الأرض. تأكيد العرض؟`))return;try{state=await api('bid',{landIndex:index,amount});render();toast('تم تثبيت العرض وخصم المبلغ')}catch(error){toast(error.message)}}
async function markAuctionSeen(){try{state=await api('auctionSeen');render()}catch(error){toast(error.message)}}
async function markMissionRead(){try{state=await api('missionRead');render()}catch(error){toast(error.message)}}
async function questionLevel(level){try{state=await api('chooseQuestion',{level});render()}catch(error){toast(error.message)}}
async function sendAnswer(index){try{state=await api('answer',{index});render()}catch(error){toast(error.message)}}
async function finishPhase(){try{state=await api('finishPhase');render()}catch(error){toast(error.message)}}

function openModal(html){const modal=$('#modal');modal.innerHTML=`<div class="modal">${html}</div>`;modal.classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function qtyTicket(title,max,confirm){openModal(`<button class="modal-close" onclick="closeModal()">×</button><h2>${title}</h2><label class="qty-label">الكمية<input id="modalQty" type="number" min="1" max="${max}" value="1"></label><button class="btn order-confirm" onclick="${confirm}">إبرام الصفقة</button>`)}
function openMarketOrder(resource,side){const max=side==='buy'?Math.floor(state.me.cash/state.prices[resource]):state.me.res[resource];if(max<1)return toast('لا توجد كمية متاحة');qtyTicket(`${side==='buy'?'شراء':'بيع'} ${R[resource].n}`,max,`marketOrder('${resource}','${side}')`)}
async function marketOrder(resource,side){try{const quantity=Number($('#modalQty').value);state=await api('marketOrder',{resource,side,quantity});closeModal();render();toast('تم إبرام الصفقة')}catch(error){toast(error.message)}}
async function buyMysteryBox(){if(!confirm('شراء صندوق عشوائي مقابل 2,000 ريال؟ قد يكون فارغًا.'))return;try{state=await api('buyBox');const result=state.me.lastBox;render();openModal(`<div class="box-result"><div class="mystery-box opened">${result.type==='empty'?'∅':'!'}</div><span class="step">نتيجة الصندوق</span><h2>${result.text}</h2><button class="btn" onclick="closeModal()">متابعة السوق</button></div>`)}catch(error){toast(error.message)}}
function openStockOrder(resource,side){const max=side==='buy'?Math.floor(state.me.cash/state.stockPrices[resource]):state.me.stocks[resource];if(max<1)return toast('لا توجد كمية متاحة');qtyTicket(`${side==='buy'?'شراء':'بيع'} سهم ${R[resource].n}`,max,`stockOrder('${resource}','${side}')`)}
async function stockOrder(resource,side){try{const quantity=Number($('#modalQty').value);state=await api('stockOrder',{resource,side,quantity});closeModal();render();toast('تم تنفيذ أمر الأسهم')}catch(error){toast(error.message)}}
function openTrade(){const players=state.players.filter(player=>player.id!==state.me.id&&!player.stageDone),options=Object.keys(R).map(key=>`<option value="${key}">${R[key].i} ${R[key].n}</option>`).join('');if(!players.length)return toast('لا يوجد قبطان متاح للمقايضة');openModal(`<button class="modal-close" onclick="closeModal()">×</button><h2>قدّم عرض مقايضة</h2><label class="qty-label">إلى<select id="tradeTo">${players.map(player=>`<option value="${player.id}">${player.name}</option>`).join('')}</select></label><div class="offer-builder"><div><label>أعطي</label><select id="tradeGive">${options}</select><input id="tradeGiveQty" type="number" min="1" value="1"></div><div class="swap-mark">⇄</div><div><label>أطلب</label><select id="tradeWant">${options}</select><input id="tradeWantQty" type="number" min="1" value="1"></div></div><button class="btn order-confirm" onclick="sendTrade()">إرسال العرض</button>`)}
async function sendTrade(){try{state=await api('createTrade',{to:$('#tradeTo').value,give:$('#tradeGive').value,giveQty:Number($('#tradeGiveQty').value),want:$('#tradeWant').value,wantQty:Number($('#tradeWantQty').value)});closeModal();render();toast('تم إرسال العرض')}catch(error){toast(error.message)}}
async function respondTrade(tradeId,accept){try{state=await api('respondTrade',{tradeId,accept});render();toast(accept?'تمت الصفقة':'رُفض العرض')}catch(error){toast(error.message)}}
function openMyShip(){const ship=state.ships.find(item=>item.id===state.me.ship);if(!ship)return;openModal(`<button class="modal-close" onclick="closeModal()">×</button><span class="step">باخرتي</span><h2>${ship.name}</h2>${Object.entries(ship.need).map(([key,need])=>{const have=state.me.res[key],percent=Math.min(100,Math.round(have/need*100));return `<div class="cargo-line"><div><b>${R[key].i} ${R[key].n}</b><span>${have} من ${need} — المتبقي ${Math.max(0,need-have)}</span></div><div class="progress"><i style="width:${percent}%"></i></div></div>`}).join('')}<div class="reward"><b>المهمة السرية: ${state.me.mission?.title||'لم تُكشف بعد'}</b><br>${state.me.mission?.text||''}<br>${state.me.missionDone?'✅ تم الإنجاز':state.me.mission?'المكافأة: '+state.me.mission.reward:''}</div>${state.me.shipComplete?'<button class="btn send-ship" onclick="sendShip()">🚢 إرسال الباخرة والفوز الآن</button>':'<p class="muted">أكمل جميع المتطلبات ليظهر زر إرسال الباخرة.</p>'}`)}
async function sendShip(){if(!confirm('إرسال الباخرة الآن؟ ستتوقف اللعبة ويُعلن فوزك فورًا.'))return;try{closeModal();state=await api('sendShip');render()}catch(error){toast(error.message)}}

if(IS_DEMO){session?resumeSession():createDemo()}else home();
