const $ = selector => document.querySelector(selector), app = $('#app');
const R = { oil:{n:'النفط',i:'🛢️'}, gas:{n:'الغاز',i:'🔥'}, gold:{n:'الذهب',i:'🪙'}, iron:{n:'الحديد',i:'⚙️'} };
const PHASES = { lobby:'اللوبي', ship:'اختيار الباخرة', auction:'مزاد الأراضي', mission:'المهمة السرية', questionSelect:'اختيار السؤال', question:'الأسئلة', market:'السوق والمقايضات', stocks:'سوق الأسهم', news:'نشرة الأخبار', finished:'النتيجة' };
const INTRO = [
  { image:'ships.png', title:'اختر باخرتك', text:'كل قبطان يبدأ بـ 5,000 ريال ويختار باخرة واحدة. للفوز عليك جمع جميع الموارد المطلوبة لباخرتك.' },
  { image:'lands.png', title:'زايدوا على أرض واحدة', text:'تُعرض الأراضي واحدة بعد الأخرى. الجميع يزايد بمضاعفات 500، وعند رسو الأرض على قبطان لا يستطيع أخذ أرض ثانية في الجولة.' },
  { image:'lands.png', title:'اكتشف موارد أرضك', text:'بعد رسو المزاد تحصل من أرضك على نفط وغاز وذهب وحديد بكميات مخفية، ثم يقرأ كل قبطان مهمته السرية.' },
  { image:'market.png', title:'الأسئلة ثم السوق', text:'يختار الجميع مستوى السؤال ويجيبون في الوقت نفسه. لا يفتح السوق حتى ينتهي آخر قبطان، ثم تستطيع البيع والشراء والمقايضة.' },
  { image:'news.png', title:'الأسهم والنشرة والفوز', text:'بعد انتهاء الجميع من السوق تفتح البورصة، ثم تعلن النشرة تغيرات الأسعار. أول من يكمل حمولة باخرته يُعلن فائزًا في النشرة.' }
];

let session = JSON.parse(localStorage.getItem('oil-land-session') || 'null');
let state = null, poller = null, clock = null, lastRender = '', bidAmount = 500, seenLand = null;
const fmt = number => new Intl.NumberFormat('ar-SA').format(number || 0);

function toast(text){const element=$('#toast');element.textContent=text;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),2600)}
async function api(action, extra={}){const payload={action,...extra};if(session){payload.code=session.code;payload.token=session.token}const response=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'تعذر تنفيذ الطلب');if(action==='create'||action==='join')return data;return data.state||data}
function saveSession(value){session=value;localStorage.setItem('oil-land-session',JSON.stringify(value))}
function clearSession(){session=null;state=null;localStorage.removeItem('oil-land-session');clearInterval(poller);location.href='/'}

function home(){
  const code=new URLSearchParams(location.search).get('room')?.toUpperCase();
  app.innerHTML=`<div class="screen"><div class="noise"></div><div class="hero"><div class="brand"><small>لعبة جماعية مباشرة</small><h1>أرض<br>النفط</h1><p>سباق اقتصادي جماعي: مزاد، موارد، معرفة، سوق، أسهم ومهمات سرية.</p>${code?`<div class="join-box"><div class="room-chip">الغرفة ${code}</div><input id="captainName" class="input" maxlength="20" placeholder="اسم القبطان"><button class="btn" onclick="joinRoom('${code}')">دخول الغرفة</button><button class="btn ghost" onclick="location.href='/'">رجوع</button></div>`:`<div class="home-actions"><button class="btn" onclick="showIntro(0)">لعبة جديدة</button><button class="btn secondary" onclick="showJoin()">دخول برمز غرفة</button><button class="btn ghost" onclick="showIntro(0,true)">كيف نلعب؟</button></div><div id="joinArea"></div>`}</div><div class="hero-art"></div></div></div>`;
}
function showJoin(){$('#joinArea').innerHTML=`<div class="join-box"><input id="roomCode" class="input" maxlength="5" placeholder="رمز الغرفة"><input id="captainName" class="input" maxlength="20" placeholder="اسم القبطان"><button class="btn" onclick="joinRoom()">انضمام</button></div>`}
function showIntro(index,viewOnly=false){const slide=INTRO[index];app.innerHTML=`<div class="screen intro-screen"><div class="noise"></div><section class="intro-card"><div class="intro-picture" style="background-image:linear-gradient(180deg,transparent,#07161ddd),url('${slide.image}')"></div><div class="intro-copy"><span class="step">شرح اللعبة ${index+1} من ${INTRO.length}</span><h1>${slide.title}</h1><p>${slide.text}</p><div class="intro-dots">${INTRO.map((_,i)=>`<i class="${i===index?'active':''}"></i>`).join('')}</div><div class="intro-actions">${index?`<button class="btn ghost" onclick="showIntro(${index-1},${viewOnly})">السابق</button>`:'<button class="btn ghost" onclick="home()">رجوع</button>'}${index<INTRO.length-1?`<button class="btn" onclick="showIntro(${index+1},${viewOnly})">التالي</button>`:viewOnly?'<button class="btn" onclick="home()">فهمت</button>':'<button class="btn" onclick="createRoom()">إنشاء الغرفة</button>'}</div></div></section></div>`}
async function createRoom(){try{const used=JSON.parse(localStorage.getItem('oil-land-used-questions-v1')||'[]');const data=await api('create',{usedQuestionIds:used});saveSession({code:data.code,token:data.token,role:'host'});state=data.state;startPolling();render()}catch(error){toast(error.message)}}
async function joinRoom(forced){try{const code=(forced||$('#roomCode')?.value||'').trim().toUpperCase(),name=$('#captainName').value.trim();if(!code||!name)return toast('اكتب الرمز واسم القبطان');session={code,token:'',role:'player'};const data=await api('join',{name});saveSession({code,token:data.token,role:'player'});state=data.state;startPolling();render()}catch(error){session=null;toast(error.message)}}
async function refresh(){if(!session)return;try{const next=await api('state');if(next.usedQuestionIds)localStorage.setItem('oil-land-used-questions-v1',JSON.stringify(next.usedQuestionIds));const signature=JSON.stringify(next);state=next;if(signature!==lastRender){lastRender=signature;render()}updateClock()}catch(error){toast(error.message);if(/غير موجودة|رمز/.test(error.message))clearSession()}}
function startPolling(){clearInterval(poller);poller=setInterval(refresh,1000);clearInterval(clock);clock=setInterval(updateClock,250)}
function updateClock(){const element=$('#globalClock');if(!element||!state)return;const left=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));element.textContent=state.deadline?left:'--';element.parentElement?.classList.toggle('danger',left<=10&&left>0)}

function gameHeader(){return `<div class="topbar"><div class="logo">أرض النفط <small>#${state.code}</small></div><div class="stats"><div class="pill">${PHASES[state.phase]}</div><div class="pill">الجولة <b>${state.round}</b></div>${state.me?`<div class="pill">الرصيد <b>${fmt(state.me.cash)}</b></div>`:''}<div class="clock-ring"><small>الوقت</small><b id="globalClock">--</b></div></div></div>`}
function shell(content,bg=''){app.innerHTML=`<div class="screen online-screen"><div class="noise"></div>${bg}${gameHeader()}<main class="main">${content}</main></div>`;updateClock()}
function progressStatus(player){if(state.phase==='ship')return player.shipChosen?'اختار الباخرة':'يختار الآن';if(state.phase==='auction')return player.hasLand?`امتلك ${player.land}`:'ينتظر أرضه';if(state.phase==='mission')return player.missionRead?'قرأ المهمة':'يقرأ المهمة';if(state.phase==='questionSelect')return player.questionChosen?'اختار السؤال':'يختار المستوى';if(state.phase==='question')return player.answered?'أجاب':'يجيب الآن';if(['market','stocks'].includes(state.phase))return player.stageDone?'انتهى':'ما زال يعمل';return player.connected?'متصل':'غير متصل'}
function playerList(){return `<div class="online-players">${state.players.map(player=>`<div class="online-player ${player.connected?'':'offline'} ${progressStatus(player).includes('انته')||progressStatus(player).includes('اختار')||progressStatus(player).includes('قرأ')||progressStatus(player).includes('أجاب')||progressStatus(player).includes('امتلك')?'done':''}"><i>${player.hasLand?'⛽':player.shipChosen?'🚢':'⚓'}</i><b>${player.name}</b><small>${progressStatus(player)}</small></div>`).join('')}</div>`}
function waitingCard(title,text){return `<section class="reveal wait-card"><div class="waiting-radar"></div><span class="step">الجميع يتحرك معًا</span><h2>${title}</h2><p>${text}</p>${playerList()}</section>`}

function render(){if(!state)return home();if(state.host)renderHost();else renderPlayer()}
function renderHost(){
  if(state.phase==='lobby')return hostLobby();
  if(state.phase==='auction')return hostAuction();
  if(state.phase==='news')return newsScreen(true);
  if(state.phase==='finished')return resultScreen();
  const extra=state.phase==='market'?marketBoard():state.phase==='stocks'?stockBoard(true):'';
  shell(`<section class="host-stage"><span class="step">شاشة العرض</span><h1>${PHASES[state.phase]}</h1><p>${state.message}</p>${playerList()}${extra}<button class="btn host-next" onclick="advance()">إنهاء الوقت والانتقال</button></section>`,['market','stocks'].includes(state.phase)?'<div class="market-bg"></div>':'');
}
function hostLobby(){const joinUrl=`${location.origin}/?room=${state.code}`;shell(`<section class="lobby-layout"><div><span class="step">غرفة جديدة</span><h1>امسح الباركود وانضم</h1><div class="code-big">${state.code}</div><p>${state.players.length} قباطنة متصلون</p>${playerList()}<button class="btn" ${state.players.length<2?'disabled':''} onclick="startGame()">ابدأ اللعبة للجميع</button><button class="btn ghost" onclick="clearSession()">إغلاق الغرفة</button></div><div class="qr-card"><img src="/api/qr?text=${encodeURIComponent(joinUrl)}" alt="باركود الدخول"><small>${joinUrl}</small></div></section>`,`<div class="lands-bg"></div>`)}
function auctionCard(){const land=state.auction.currentLand,bid=state.auction.currentBid;return `<section class="auction-focus"><div class="auction-photo"></div><div class="auction-info"><span class="step">الأرض ${state.auction.landIndex+1}</span><h1>${land.name}</h1><p>${land.description}</p><div class="highest-bid"><small>أعلى مزايدة</small><b>${bid?fmt(bid.amount):'500'}</b><span>${bid?bid.name:'لم يزايد أحد بعد'}</span></div></div></section>${auctionResults()}`}
function auctionResults(){const won=state.auction.results.filter(item=>!item.skipped);if(!won.length)return '';return `<div class="auction-winners"><h3>الأراضي التي رست</h3>${won.map(item=>`<div><span>${item.land}</span><b>${item.name}</b><small>${fmt(item.amount)} ريال</small></div>`).join('')}</div>`}
function hostAuction(){shell(`<div class="stage-head"><div><span class="step">مزاد حي للجميع</span><h2>أرض واحدة في كل مرة</h2><p>${state.message}</p></div></div>${auctionCard()}${playerList()}<button class="btn host-next" onclick="advance()">إرساء الأرض الآن</button>`,`<div class="lands-bg"></div>`)}
function marketBoard(){return `<div class="market-public">${Object.keys(R).map(key=>`<div><span>${R[key].i} ${R[key].n}</span><b>${fmt(state.prices[key])}</b></div>`).join('')}</div>`}

function renderPlayer(){if(state.phase==='lobby')return waiting();if(state.phase==='ship')return chooseShip();if(state.phase==='auction')return playerAuction();if(state.phase==='mission')return secretMission();if(state.phase==='questionSelect')return chooseQuestion();if(state.phase==='question')return answerQuestion();if(state.phase==='market')return market();if(state.phase==='stocks')return stocks();if(state.phase==='news')return newsScreen(false);if(state.phase==='finished')return resultScreen()}
function waiting(){shell(waitingCard(`أهلًا بك يا ${state.me.name}`,'تم تسجيلك. انتظر المضيف حتى يبدأ السباق.'))}
function chooseShip(){if(state.me.ship)return shell(waitingCard('تم اختيار باخرتك','لن يبدأ المزاد حتى يختار جميع القباطنة.'));shell(`<div class="stage-head"><div><span class="step">القرار الأول</span><h2>اختر باخرتك</h2><p>اختيارك نهائي، والفوز بإكمال جميع احتياجاتها.</p></div></div><div class="grid ships">${state.ships.map((ship,index)=>`<article class="card"><div class="ship-img s${index+1}"></div><div class="card-body"><h3>${ship.name}</h3><div class="requirements">${Object.entries(ship.need).map(([key,value])=>`<div class="req"><span>${R[key].i}</span>${value} ${R[key].n}</div>`).join('')}</div><button class="btn" onclick="chooseShipAction('${ship.id}')">اختيار هذه الباخرة</button></div></article>`).join('')}</div>`)}
function playerAuction(){
  const minimum=(state.auction.currentBid?.amount||0)+500;
  if(seenLand!==state.auction.landIndex){seenLand=state.auction.landIndex;bidAmount=minimum}
  bidAmount=Math.max(bidAmount,minimum);
  const controls=state.me.land?`<div class="owned-land"><b>رست عليك ${state.me.land}</b><span>لا يمكنك أخذ أرض ثانية هذه الجولة. تابع المزاد وانتظر الآخرين.</span></div>`:`<div class="bid-panel"><div><small>مزايدتك الحالية</small><div class="bid-price" id="bidValue">${fmt(bidAmount)}</div></div><div class="bid-actions"><button class="btn secondary" onclick="changeBid(-500)">−500</button><button class="btn secondary" onclick="changeBid(500)">+500</button><button class="btn" onclick="placeBid()">زايد الآن</button></div></div>`;
  shell(`${auctionCard()}${controls}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="lands-bg"></div>`);
}
function secretMission(){if(state.me.missionRead)return shell(waitingCard('تمت قراءة مهمتك','تبدأ الأسئلة عندما يضغط جميع القباطنة «قرأتها».'));const mission=state.me.mission;shell(`<section class="mission-reveal"><div class="mission-seal">!</div><span class="step">سري للغاية</span><h1>${mission.title}</h1><p>${mission.text}</p><div class="mission-reward">المكافأة: <b>${mission.reward}</b></div><button class="btn" onclick="markMissionRead()">قرأتها ومستعد</button></section>`)}
function chooseQuestion(){if(state.me.difficulty)return shell(waitingCard('تم اختيار سؤالك','لن تبدأ الأسئلة حتى يختار الجميع.'));shell(`<div class="stage-head"><div><span class="step">تحدي المعرفة</span><h2>اختر مستوى السؤال</h2><p>يبدأ عداد الأسئلة للجميع بعد آخر اختيار.</p></div></div><div class="grid questions"><article class="card qcard easy" onclick="questionLevel('easy')"><h3>سهل</h3><div class="money">1,000</div></article><article class="card qcard medium" onclick="questionLevel('medium')"><h3>متوسط</h3><div class="money">3,000</div></article><article class="card qcard hard" onclick="questionLevel('hard')"><h3>صعب</h3><div class="money">5,000</div></article></div>`)}
function answerQuestion(){if(state.me.answered)return shell(waitingCard(state.me.answerCorrect?'إجابة صحيحة ✓':'تم تسجيل إجابتك',state.me.answerCorrect?'أضيفت الجائزة إلى رصيدك. انتظر بقية القباطنة.':`الإجابة الصحيحة: ${state.me.correctAnswer||'تظهر بعد الإجابة'}. انتظر بقية القباطنة.`));const question=state.me.question;if(!question)return shell(waitingCard('جارٍ تجهيز السؤال','لحظات ويبدأ التحدي للجميع.'));shell(`<section class="question-box"><span class="step">الجائزة ${fmt(state.me.prize)}</span><h3>${question.q}</h3><div class="answers">${question.a.map((answer,index)=>`<button class="answer" onclick="sendAnswer(${index})">${answer}</button>`).join('')}</div></section>`)}

function resourceBar(){return `<div class="resource-bar"><div>💰 <b>${fmt(state.me.cash)}</b></div>${Object.keys(R).map(key=>`<div>${R[key].i} <b>${state.me.res[key]}</b></div>`).join('')}</div>`}
function phaseFinishButton(){return `<section class="finish-strip"><div><b>خلصت؟</b><span>بعد الضغط تنتظر بقية القباطنة ولا يمكنك تنفيذ عمليات جديدة.</span></div><button class="btn" onclick="finishPhase()">انتهيت من هذه المرحلة</button></section>`}
function market(){if(state.me.stageDone)return shell(`${resourceBar()}${waitingCard('انتهيت من السوق','ننتقل إلى الأسهم عند انتهاء الجميع أو انتهاء الوقت.')}`,'<div class="market-bg"></div>');shell(`${resourceBar()}<div class="stage-head"><div><span class="step">السوق للجميع</span><h2>بيع، اشترِ وقايض</h2><p>الجميع في السوق الآن، ولن تفتح البورصة قبل انتهاء الجميع.</p></div></div><div class="market-resource-grid">${Object.keys(R).map(key=>`<article class="market-resource"><i>${R[key].i}</i><h3>${R[key].n}</h3><b>${fmt(state.prices[key])}</b><small>للشراء • البيع ${fmt(Math.floor(state.prices[key]*.78))}</small><div><button class="mini" onclick="openMarketOrder('${key}','buy')">شراء</button><button class="mini sell" onclick="openMarketOrder('${key}','sell')">بيع</button></div></article>`).join('')}</div><section class="captains-council"><div class="council-head"><div><span class="step">مجلس القباطنة</span><h2>المقايضات المباشرة</h2></div><button class="btn propose-btn" onclick="openTrade()">＋ قدّم عرضك</button></div>${tradeInbox()}${state.me.outgoingTrades.length?`<h3>عروضك المرسلة</h3>${state.me.outgoingTrades.map(trade=>`<div class="trade-line">إلى ${state.players.find(player=>player.id===trade.to)?.name}: ${trade.giveQty} ${R[trade.give].i} مقابل ${trade.wantQty} ${R[trade.want].i}<small>بانتظار الرد</small></div>`).join('')}`:''}</section>${phaseFinishButton()}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="market-bg"></div>`)}
function tradeInbox(){if(!state.me.incomingTrades.length)return '<p class="muted">لا توجد عروض واردة الآن.</p>';return state.me.incomingTrades.map(trade=>`<div class="trade-line"><b>${trade.fromName}</b><span>يعطيك ${trade.giveQty} ${R[trade.give].i} مقابل ${trade.wantQty} ${R[trade.want].i}</span><div><button class="mini" onclick="respondTrade('${trade.id}',true)">قبول</button><button class="mini sell" onclick="respondTrade('${trade.id}',false)">رفض</button></div></div>`).join('')}
function stocks(){if(state.me.stageDone)return shell(`${resourceBar()}${waitingCard('انتهيت من الأسهم','تبدأ النشرة عند انتهاء الجميع أو انتهاء الوقت.')}`,'<div class="market-bg"></div>');shell(`${resourceBar()}<div class="stage-head"><div><span class="step">البورصة للجميع</span><h2>سوق الأسهم</h2><p>نفّذ استثماراتك ثم اضغط «انتهيت».</p></div></div>${stockBoard(false)}${phaseFinishButton()}<button class="btn secondary ship-float" onclick="openMyShip()">🚢 باخرتي</button>`,`<div class="market-bg"></div>`)}
function stockBoard(host){return `<div class="stock-grid">${Object.keys(R).map(key=>{const change=state.lastChanges[key],up=change>=0;return `<article class="stock-card ${up?'stock-up':'stock-down'}"><div class="stock-title"><div class="stock-icon">${R[key].i}</div><div><small>شركة ${R[key].n}</small><h3>سهم ${R[key].n}</h3></div></div><div class="stock-price"><b>${fmt(state.stockPrices[key])}</b><span>ريال للسهم</span></div><div class="stock-change ${up?'up':'down'}"><b>${up?'▲ مرتفع':'▼ منخفض'} ${Math.abs(change).toFixed(1)}%</b></div>${!host?`<div class="stock-owned">تملك <b>${state.me.stocks[key]}</b> سهم</div><div class="stock-actions"><button class="mini" onclick="openStockOrder('${key}','buy')">شراء</button><button class="mini sell" onclick="openStockOrder('${key}','sell')">بيع</button></div>`:''}</article>`}).join('')}</div>`}
function newsScreen(host){const items=state.news.length?state.news:['الأسواق هادئة والقباطنة يترقبون الجولة القادمة.'];shell(`<section class="news-card"><span class="breaking">نشرة أرض النفط</span><div class="on-air">● على الهواء</div><div class="headline">${items[items.length-1]}</div><div class="ticker">${items.join(' • ')}</div><div class="market-summary">${Object.keys(R).map(key=>`<div class="resource"><i>${R[key].i}</i><b class="change ${state.lastChanges[key]>=0?'up':'down'}">${state.lastChanges[key]>=0?'▲':'▼'} ${Math.abs(state.lastChanges[key]).toFixed(1)}%</b><small>${R[key].n}</small></div>`).join('')}</div>${host?'<button class="btn" onclick="advance()">بدء الجولة التالية</button>':'<p>الجولة التالية تبدأ للجميع بعد النشرة.</p>'}</section>`,`<div class="news-bg"></div>`)}
function resultScreen(){const winner=state.players.find(player=>player.id===state.winner);shell(`<section class="result"><span class="step">انتهى السباق</span><h1>${winner?.name||'القبطان الفائز'}</h1><p>أكمل حمولة باخرته أولًا وأصبح سيد أرض النفط.</p><div class="ship-sail"></div><button class="btn" onclick="clearSession()">العودة للرئيسية</button></section>`,`<div class="news-bg"></div>`)}

async function startGame(){try{state=await api('start');render()}catch(error){toast(error.message)}}
async function advance(){try{state=await api('advance');render()}catch(error){toast(error.message)}}
async function chooseShipAction(ship){try{state=await api('chooseShip',{ship});render()}catch(error){toast(error.message)}}
function changeBid(delta){const minimum=(state.auction.currentBid?.amount||0)+500;bidAmount=Math.max(minimum,Math.min(state.me.cash,bidAmount+delta));$('#bidValue').textContent=fmt(bidAmount)}
async function placeBid(){try{state=await api('bid',{amount:bidAmount});bidAmount=(state.auction?.currentBid?.amount||bidAmount)+500;render()}catch(error){toast(error.message)}}
async function markMissionRead(){try{state=await api('missionRead');render()}catch(error){toast(error.message)}}
async function questionLevel(level){try{state=await api('chooseQuestion',{level});render()}catch(error){toast(error.message)}}
async function sendAnswer(index){try{state=await api('answer',{index});render()}catch(error){toast(error.message)}}
async function finishPhase(){try{state=await api('finishPhase');render()}catch(error){toast(error.message)}}

function openModal(html){const modal=$('#modal');modal.innerHTML=`<div class="modal">${html}</div>`;modal.classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function qtyTicket(title,max,confirm){openModal(`<button class="modal-close" onclick="closeModal()">×</button><h2>${title}</h2><label class="qty-label">الكمية<input id="modalQty" type="number" min="1" max="${max}" value="1"></label><button class="btn order-confirm" onclick="${confirm}">إبرام الصفقة</button>`)}
function openMarketOrder(resource,side){const max=side==='buy'?Math.floor(state.me.cash/state.prices[resource]):state.me.res[resource];if(max<1)return toast('لا توجد كمية متاحة');qtyTicket(`${side==='buy'?'شراء':'بيع'} ${R[resource].n}`,max,`marketOrder('${resource}','${side}')`)}
async function marketOrder(resource,side){try{const quantity=Number($('#modalQty').value);state=await api('marketOrder',{resource,side,quantity});closeModal();render();toast('تم إبرام الصفقة')}catch(error){toast(error.message)}}
function openStockOrder(resource,side){const max=side==='buy'?Math.floor(state.me.cash/state.stockPrices[resource]):state.me.stocks[resource];if(max<1)return toast('لا توجد كمية متاحة');qtyTicket(`${side==='buy'?'شراء':'بيع'} سهم ${R[resource].n}`,max,`stockOrder('${resource}','${side}')`)}
async function stockOrder(resource,side){try{const quantity=Number($('#modalQty').value);state=await api('stockOrder',{resource,side,quantity});closeModal();render();toast('تم تنفيذ أمر الأسهم')}catch(error){toast(error.message)}}
function openTrade(){const players=state.players.filter(player=>player.id!==state.me.id&&!player.stageDone),options=Object.keys(R).map(key=>`<option value="${key}">${R[key].i} ${R[key].n}</option>`).join('');if(!players.length)return toast('لا يوجد قبطان متاح للمقايضة');openModal(`<button class="modal-close" onclick="closeModal()">×</button><h2>قدّم عرض مقايضة</h2><label class="qty-label">إلى<select id="tradeTo">${players.map(player=>`<option value="${player.id}">${player.name}</option>`).join('')}</select></label><div class="offer-builder"><div><label>أعطي</label><select id="tradeGive">${options}</select><input id="tradeGiveQty" type="number" min="1" value="1"></div><div class="swap-mark">⇄</div><div><label>أطلب</label><select id="tradeWant">${options}</select><input id="tradeWantQty" type="number" min="1" value="1"></div></div><button class="btn order-confirm" onclick="sendTrade()">إرسال العرض</button>`)}
async function sendTrade(){try{state=await api('createTrade',{to:$('#tradeTo').value,give:$('#tradeGive').value,giveQty:Number($('#tradeGiveQty').value),want:$('#tradeWant').value,wantQty:Number($('#tradeWantQty').value)});closeModal();render();toast('تم إرسال العرض')}catch(error){toast(error.message)}}
async function respondTrade(tradeId,accept){try{state=await api('respondTrade',{tradeId,accept});render();toast(accept?'تمت الصفقة':'رُفض العرض')}catch(error){toast(error.message)}}
function openMyShip(){const ship=state.ships.find(item=>item.id===state.me.ship);if(!ship)return;openModal(`<button class="modal-close" onclick="closeModal()">×</button><span class="step">باخرتي</span><h2>${ship.name}</h2>${Object.entries(ship.need).map(([key,need])=>{const have=state.me.res[key],percent=Math.min(100,Math.round(have/need*100));return `<div class="cargo-line"><div><b>${R[key].i} ${R[key].n}</b><span>${have} من ${need} — المتبقي ${Math.max(0,need-have)}</span></div><div class="progress"><i style="width:${percent}%"></i></div></div>`}).join('')}<div class="reward"><b>المهمة السرية: ${state.me.mission?.title||'لم تُكشف بعد'}</b><br>${state.me.mission?.text||''}<br>${state.me.missionDone?'✅ تم الإنجاز':state.me.mission?'المكافأة: '+state.me.mission.reward:''}</div>`)}

if(session){refresh().then(startPolling)}else home();
